image:
  repository: my-docker-repo/ecommerce
  tag: latest
  pullPolicy: Always

replicaCount: 3

service:
  type: LoadBalancer
  port: 80

resources:
  limits:
    cpu: "500m"
    memory: "1Gi"
  requests:
    cpu: "250m"
    memory: "512Mi"
